#!/bin/dash

file=$(fd . --type f | fzf --layout=reverse --preview="bat --plain --color=always {}")

[ -z "$file" ] && return 1

file=$(echo "$file" | xargs realpath -q)
dir=$(echo "$file" | sed -E "s|^(.*)/.*$|\1|g")

cd "$dir"
echo "$file" | xargs "$EDITOR"
