#!/bin/dash

attachments=""
convert=""

for arg in "$@"; do
    [ "$arg" = "-c" ] && { convert=",subject='Convert'"; continue; }
    [ -f "$arg" ] || { printf "$arg is not a file, skipping..."; continue; }
    attachments="${attachments}file://$(realpath "$arg"),"
done

attachments=$(printf "$attachments" | sed -E "s/^(.*),$/\1/")

[ -z "$attachments" ] && { printf "Usage: to-kindle <file1> <fileN>"; exit 1; }

thunderbird -compose "to='minhtuannguyen642005_XZtLsQ@kindle.com,\
    minhtuannguyen642005_vX39vi@kindle.com',attachment='\
    $attachments'$convert" > /dev/null 2>&1
