#!/bin/python3

import smtplib
import sys
import os
import mimetypes

from email.message import EmailMessage

if len(sys.argv) <= 1:
    print(f"Usage: {os.path.basename(sys.argv[0])} <file1> <fileN>")
    sys.exit(1)

email = os.getenv('EMAIL')
password = os.getenv('EMAIL_APP_PASSWORD')

if not email:
    print("Environmental variable 'EMAIL' is not set")
    sys.exit(1)
if not password:
    print("Environmental variable 'EMAIL_APP_PASSWORD' is not set")
    sys.exit(1)


attachments = []
for file_name in sys.argv[1:]:
    if not os.path.isfile(file_name):
        print(f"{file_name} is not a file, skipping...")
        continue
    attachments.append(file_name)

if not attachments:
    sys.exit(1)

msg = EmailMessage()
msg['From'] = email
msg['To'] = 'minhtuannguyen642005_XZtLsQ@kindle.com, \
        minhtuannguyen642005_vX39vi@kindle.com'

for file_name in attachments:
    mime_type, _ = mimetypes.guess_type(file_name)

    if mime_type is None:
        maintype, subtype = 'application', 'octet-stream'
    else:
        maintype, subtype = mime_type.split('/')

    with open(file_name, 'rb') as file:
        file_data = file.read()

    msg.add_attachment(file_data, maintype=maintype, subtype=subtype,
                       filename=os.path.basename(file_name))

with smtplib.SMTP('smtp.gmail.com', 587) as server:
    server.starttls()
    server.login(email, password)
    server.send_message(msg)

print("Sent")
