#!/bin/dash

remote_dest="z5662654@login.cse.unsw.edu.au:/home/z5662654/Workspace/"

[ "$#" -lt 1 ] && { echo "Please provide a command"; exit 1; }

case "$1" in
    mount)
        mountpoint -q /mnt/UNSW_remote/ || 
            sshfs -o reconnect,ServerAliveInterval=15,ServerAliveCountMax=3 z5662654@login.cse.unsw.edu.au:/home/z5662654/ /mnt/UNSW_remote/
        ;;
    umount)
        mountpoint -q /mnt/UNSW_remote/ &&
            umount /mnt/UNSW_remote/
        ;;
    ssh)
        ssh -Y z5662654@login.cse.unsw.edu.au
        ;;
    push)
        shift
        rsync $@ $remote_dest
        ;;
    pull)
        rsync ${remote_dest}$2 .
        ;;
    *)
        echo "Usage: cse {mount|umount|ssh}"
        exit 1
        ;;
esac
